// flow-typed signature: 76f056e72685c0acf1ec1e244a8d9638
// flow-typed version: <<STUB>>/bindings_v^1.3.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bindings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bindings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bindings/bindings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bindings/bindings.js' {
  declare module.exports: $Exports<'bindings/bindings'>;
}
