// flow-typed signature: c1db92020e1bb17504bf5df117492980
// flow-typed version: <<STUB>>/node-addon-api_v^1.4.0/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-addon-api'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-addon-api' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-addon-api/tools/conversion' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-addon-api/index' {
  declare module.exports: $Exports<'node-addon-api'>;
}
declare module 'node-addon-api/index.js' {
  declare module.exports: $Exports<'node-addon-api'>;
}
declare module 'node-addon-api/tools/conversion.js' {
  declare module.exports: $Exports<'node-addon-api/tools/conversion'>;
}
